# Generated by Django 5.1.6 on 2025-05-07 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_paymentcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bonus_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_spent',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
