# Generated by Django 5.1.6 on 2025-06-18 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_bonus_points_user_total_spent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bonus_points',
        ),
    ]
