# Generated by Django 5.1.6 on 2025-06-19 01:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomBouquet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ai_bouquets/')),
                ('description', models.TextField()),
                ('greeting_message', models.TextField(blank=True, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('postcard', models.ForeignKey(blank=True, limit_choices_to={'category': 'postcard'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomBouquetAccessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessory_type', models.CharField(max_length=20)),
                ('bouquet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to='yourwish.custombouquet')),
                ('product', models.ForeignKey(limit_choices_to={'category__in': ['wrapping_paper', 'ribbon']}, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='CustomBouquetFlower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('bouquet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flowers', to='yourwish.custombouquet')),
                ('product', models.ForeignKey(limit_choices_to={'category': 'flower'}, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
