# Generated by Django 5.1.6 on 2025-03-26 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_flower_ingredients_product_seasonality_and_more'),
        ('yourwish', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='custombouquetaccessory',
            name='accessory_type',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='custombouquet',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='custombouquetaccessory',
            name='product',
            field=models.ForeignKey(limit_choices_to={'category__in': ['wrapping_paper', 'ribbon']}, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AlterField(
            model_name='custombouquetflower',
            name='product',
            field=models.ForeignKey(limit_choices_to={'category': 'flower'}, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AlterField(
            model_name='custombouquetflower',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
