# Generated by Django 5.1.6 on 2025-03-26 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('yourwish', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='customBouquet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='yourwish.custombouquet'),
            preserve_default=False,
        ),
    ]
