# Generated by Django 5.1.6 on 2025-03-26 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_cartitem_product_cartitem_custombouquet'),
        ('products', '0002_product_flower_ingredients_product_seasonality_and_more'),
        ('yourwish', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='customBouquet',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='custom_bouquet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yourwish.custombouquet'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
