# Generated by Django 5.1.6 on 2025-03-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='custom_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
